RestoCash/protected/models/Room.php
<?php

/**
 * This is the model class for table "{{room}}".
 *
 * The followings are the available columns in table '{{room}}':
 * @property integer $id
 * @property string $name
 * @property boolean $disabled
 *
 * The followings are the available model relations:
 * @property Table[] $tables
 */
class Room extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{room}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>255),
			array('disabled', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, disabled', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'tables' => array(self::HAS_MANY, 'Table', 'room'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('Room','ID'),
			'name' => Yii::t('Room','Name'),
			'disabled' => Yii::t('Room','Disabled'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('disabled',$this->disabled);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Room the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

RestoCash/protected/controllers/OrderController.php
<?php

class OrderController extends Controller
{
    public $layout='//layouts/column1withoutfooter';

	public function actionIndex()
	{
        if ($id_table = (int)$_GET['idtable']) {
            Yii::app()->session['table'] = $id_table;
            $this->render('index');
        } else {
            Yii::app()->user->setFlash('warning','Please, select a table!');
            $this->redirect(array('room/show'));
        }
	}

    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('add','view'),
                'users'=>array('*'),
            ),
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','show'),
                'roles'=>array('owner'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    public function actionAdd() {
        if (!Yii::app()->session['table']) {
            Yii::app()->user->setFlash('warning','Please, select a table!');
            $this->redirect(array('room/show'));
        }
        $item = myItem::model()->findByPk($_GET['id']);
        if (!$order = myOrder::model()->find(array('condition'=>'table_id='.Yii::app()->session['table'].' and status <> 7'))) {
            $order = new myOrder();
            $order->table_id = Yii::app()->session['table'];
            $order->status=2;
            $order->user=Yii::app()->user->id;
            $order->create_time = new CDbExpression('NOW()');
            $order->update_time = new CDbExpression('NOW()');
            $order->save();
        } else {
            $order->update_time = new CDbExpression('NOW()');
            $order->save();
        }

        $order_detail = new MyOrderDetail();
        $order_detail->order = $order->id;
        $order_detail->item = $item->id;
        $order_detail->category = $item->category;
        //parent is parent of order_detail and not item !!!
        $order_detail->parent = $item->parent;

        $order_detail->price = $item->price;
        if ($item->price > 0) {
            $order_detail->price_vat = $item->price * ($item->vat0->name/100);
        } else {
            $order_detail->price_vat = 0;
        }
        $order_detail->vat = $item->vat0->name;
        $order_detail->user=Yii::app()->user->id;
        $order_detail->save();

        $order->total = $order_detail->getTotal();
        $order->save();
    }



}

RestoCash/protected/controllers/RoomController.php
<?php

class RoomController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

    public function actionShow()
    {
        $this->layout='//layouts/column1withoutfooter';
        if ($_GET['idroom']) {
            Yii::app()->session['room'] = $_GET['idroom'];
        }
        $this->render('show');
    }

    public function actionSavepos() {
        if ($_POST['type_id'] == 1) {
            myTable::model()->updateByPk($_POST['need_id'], array('x' => $_POST['x'],'y' => $_POST['y']));
        } else {
            myDecor::model()->updateByPk($_POST['need_id'], array('x' => $_POST['x'],'y' => $_POST['y']));
        }

    }


    public function getRooms() {
        $res = array();
        foreach (myRoom::model()->findAll('disabled=:disabled', array(':disabled'=>0)) as $room) {
            if ($room->id == Yii::app()->session['room']) {
                $res[] = array('label' => $room->name, 'active'=>true, 'url' => Yii::app()->createUrl('room/show', array('idroom' => $room->id)));
            } else {
                $res[] = array('label' => $room->name, 'active'=>false, 'url' => Yii::app()->createUrl('room/show', array('idroom' => $room->id)));
            }

        }
        return $res;
    }


    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','show','savepos'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
                'roles'=>array('owner'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new myRoom;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['myRoom']))
		{
			$model->attributes=$_POST['myRoom'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['myRoom']))
		{
			$model->attributes=$_POST['myRoom'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('myRoom');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new myRoom('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['myRoom']))
			$model->attributes=$_GET['myRoom'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=myRoom::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='room-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

RestoCash/protected/views/room/_form.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'id'=>'room-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="help-block">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->checkBoxRow($model,'disabled'); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>$model->isNewRecord ? 'Create' : 'Save',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

RestoCash/protected/views/room/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

	<?php echo $form->textFieldRow($model,'name',array('class'=>'span5','maxlength'=>255)); ?>

	<?php echo $form->checkBoxRow($model,'disabled'); ?>

	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array(
			'buttonType'=>'submit',
			'type'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

RestoCash/protected/views/room/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('disabled')); ?>:</b>
	<?php echo CHtml::encode($data->disabled); ?>
	<br />


</div>

RestoCash/protected/views/room/admin.php
<?php
$this->breadcrumbs=array(
	'Rooms'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Room','url'=>array('index'),'icon'=>'book'),
	array('label'=>'Create Room','url'=>array('create'),'icon'=>'plus'),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('room-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Rooms</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'room-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
    'type'=>'striped bordered condensed',
	'columns'=>array(
		'id',
		'name',
		'disabled',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
		),
	),
)); ?>

RestoCash/protected/views/room/create.php
<?php
$this->breadcrumbs=array(
	'Rooms'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Room','url'=>array('index'),'icon'=>'book'),
	array('label'=>'Manage Room','url'=>array('admin'),'icon'=>'user'),
);
?>

<h1>Create Room</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

RestoCash/protected/views/room/index.php
<?php
$this->breadcrumbs=array(
	'Rooms',
);

$this->menu=array(
	array('label'=>'Create Room','url'=>array('create'),'icon'=>'plus'),
	array('label'=>'Manage Room','url'=>array('admin'),'icon'=>'user'),
);
?>

<h1>Rooms</h1>

<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

RestoCash/protected/views/room/show.php
<?php
/* @var $this RoomsController */

$this->widget('bootstrap.widgets.TbMenu', array(
    'type'=>'pills', // '', 'tabs', 'pills' (or 'list')
    'stacked'=>false, // whether this is a stacked menu
    'items'=>$this->getRooms(),
));


$str_js = "
$(function() {
    $( '#room div' ).draggable({
        stack: '#room div',
        stop: function(event, ui) {
            var pos_x = ui.offset.left;
            var pos_y = ui.offset.top;
            var need = ui.helper.data('need');
            var type = ui.helper.data('type');

            $.ajax({
                type: 'POST',
                url: 'savepos',
                data: { x: pos_x, y: pos_y, need_id: need, type_id: type}
            })
        }
    });
});
";
Yii::app()->clientScript->registerScript('sortable-project', $str_js);
?>

<div id="room" style="width: 100%;">
    <?php
    if ($decos = myDecor::model()->findAll('room=:room AND disabled=:disabled', array(':room'=>Yii::app()->session['room'],':disabled'=>0))) {
        foreach ($decos as $deco) {
            $this->beginWidget('zii.widgets.jui.CJuiDraggable',array(
                'options'=>array(
                    'opacity' => 0.35,
                    'cursor'=>'move',
                ),
                'htmlOptions'=>array(
                    'style'=>$deco->type0->css. 'left:'.$deco->x.'px; top:'.$deco->y.'px; padding: 5px; position: absolute; text-align: center;',
                    'data-need'=>$deco->id,
                    'data-type'=>2,
                ),
                'id'=>$deco->id,
            ));
            $this->endWidget();
        }
    }


    if ($tables = myTable::model()->findAll('room=:room AND disabled=:disabled', array(':room'=>Yii::app()->session['room'],':disabled'=>0))) {
        foreach ($tables as $table) {
            $this->beginWidget('zii.widgets.jui.CJuiDraggable',array(
                'options'=>array(
                    'opacity' => 0.35,
                    'cursor'=>'move',
                ),
                'htmlOptions'=>array(
                    'style'=>$table->type0->css. 'left:'.$table->x.'px; top:'.$table->y.'px; padding: 5px; border: 1px solid #e3e3e3; background: #F4F4F4;position: absolute; text-align: center;',
                    'data-need'=>$table->id,
                    'data-type'=>1,
                ),
                'id'=>$table->id,
            ));

            $this->widget('bootstrap.widgets.TbBadge', array(
                'label'=>$table->id,
            ));


            $this->widget('bootstrap.widgets.TbLabel', array(
                'type'=>$table->status0->color,
                'label'=>$table->status0->name,
            ));
            if ((int)$table->type0->id != 6) {
                echo '</br>';

                echo '<i class="icon-user"> </i>';
                if ($table->status0->id != 1) {
                    $this->widget('bootstrap.widgets.TbBadge', array(
                        'type'=>'success',
                        'label'=>'1/'.$table->client_max,
                    ));
                } else {
                    $this->widget('bootstrap.widgets.TbBadge', array(
                        'type'=>'success',
                        'label'=>$table->client_max,
                    ));
                }
            }


            if ($table->status0->id != 1) {
                $startTime = myOrder::model()->find(array('condition'=>'table_id='.$table->id.' and status <> 7'))->create_time;
                echo '</br>';
                echo '<i class="icon-time"> </i>';
                $this->widget('bootstrap.widgets.TbBadge', array(
                    'type'=>'important',
                  //  'label'=>  date_diff($startTime, new DateTime("now"))
                ));
            }

            echo '</br>';
            $this->widget('bootstrap.widgets.TbButton', array(
                'buttonType'=>'link',
                'label'=>'Open',
                'type'=>'info',
                'url'=>$this->createUrl('order/index',array('idtable'=>$table->id)),
                'size'=>'mini',
            ));

            $this->endWidget();
        }
    }




?>
</div>

RestoCash/protected/views/room/update.php
<?php
$this->breadcrumbs=array(
	'Rooms'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Room','url'=>array('index'),'icon'=>'book'),
	array('label'=>'Create Room','url'=>array('create'),'icon'=>'plus'),
	array('label'=>'View Room','url'=>array('view','id'=>$model->id),'icon'=>'eye-open'),
	array('label'=>'Manage Room','url'=>array('admin'),'icon'=>'user'),
);
?>

<h1>Update Room <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

RestoCash/protected/views/room/view.php
<?php
$this->breadcrumbs=array(
	'Rooms'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List Room','url'=>array('index'),'icon'=>'book'),
	array('label'=>'Create Room','url'=>array('create'),'icon'=>'plus'),
	array('label'=>'Update Room','url'=>array('update','id'=>$model->id),'icon'=>'pencil'),
	array('label'=>'Delete Room','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?'),'icon'=>'remove-circle'),
	array('label'=>'Manage Room','url'=>array('admin'),'icon'=>'user'),
);
?>

<h1>View Room #<?php echo $model->id; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
    'type'=>'striped bordered condensed',
	'attributes'=>array(
		'id',
		'name',
		'disabled',
	),
)); ?>